# TCL File Generated by Component Editor 17.0
# Tue Jun 25 22:11:10 IST 2024
# DO NOT MODIFY


# 
# Distance "distance" v1.0
#  2024.06.25.22:11:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Distance
# 
set_module_property DESCRIPTION ""
set_module_property NAME Distance
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME distance
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Video_System_video_edge_detection_0
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Dis_left_right.v VERILOG PATH D:/camera_working/Dis_left_right.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter WIDTH INTEGER 720
set_parameter_property WIDTH DEFAULT_VALUE 720
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink avalon_streaming_sink_data data Input 8
add_interface_port avalon_streaming_sink avalon_streaming_sink_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink avalon_streaming_sink_ready ready Output 1
add_interface_port avalon_streaming_sink avalon_streaming_sink_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink avalon_streaming_sink_empty empty Input 1


# 
# connection point stream_out
# 
add_interface stream_out avalon end
set_interface_property stream_out addressUnits WORDS
set_interface_property stream_out associatedClock clock
set_interface_property stream_out associatedReset reset
set_interface_property stream_out bitsPerSymbol 8
set_interface_property stream_out burstOnBurstBoundariesOnly false
set_interface_property stream_out burstcountUnits WORDS
set_interface_property stream_out explicitAddressSpan 0
set_interface_property stream_out holdTime 0
set_interface_property stream_out linewrapBursts false
set_interface_property stream_out maximumPendingReadTransactions 0
set_interface_property stream_out maximumPendingWriteTransactions 0
set_interface_property stream_out readLatency 0
set_interface_property stream_out readWaitTime 1
set_interface_property stream_out setupTime 0
set_interface_property stream_out timingUnits Cycles
set_interface_property stream_out writeWaitTime 0
set_interface_property stream_out ENABLED true
set_interface_property stream_out EXPORT_OF ""
set_interface_property stream_out PORT_NAME_MAP ""
set_interface_property stream_out CMSIS_SVD_VARIABLES ""
set_interface_property stream_out SVD_ADDRESS_GROUP ""

add_interface_port stream_out stream_out_write write Input 1
add_interface_port stream_out stream_out_writedata writedata Input 16
set_interface_assignment stream_out embeddedsw.configuration.isFlash 0
set_interface_assignment stream_out embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment stream_out embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment stream_out embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source avalon_streaming_source_data data Output 8
add_interface_port avalon_streaming_source avalon_streaming_source_empty empty Output 1
add_interface_port avalon_streaming_source avalon_streaming_source_endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source avalon_streaming_source_ready ready Input 1
add_interface_port avalon_streaming_source avalon_streaming_source_startofpacket startofpacket Output 1

